services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_storage
    ports:
      - "6333:6333"   # REST
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_storage:/qdrant_storage/storage
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_data
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama_data
    restart: unless-stopped

volumes:
  qdrant_storage:
  ollama_data:
